# Generated by Django 4.2.1 on 2023-06-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
